samples/InspectionApp/src/Salesforce/objects/GlassSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <defaultValue>&quot;3MVG9JZ_r.QzrS7g.Ouagr7SVAJB1PykHPThSvUaPbfNF2cL3kXALeErIVSIxBIBbYBTJgfUz8zdmY2f7Hkc5&quot;</defaultValue>
        <label>Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redirect_URL__c</fullName>
        <defaultValue>&quot;https://glass-developer-edition.na10.force.com/glassauth/SalesforceToGoogle&quot;</defaultValue>
        <label>Redirect URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Glass Settings</label>
</CustomObject>

samples/InspectionApp/src/Salesforce/classes/AuthorizeSalesforceController.cls
public class AuthorizeSalesforceController
{
    
    public AuthorizeSalesforceController()
    {
    }
    
    public PageReference doRedirect()
    {
		GlassSettings__c settings = GlassSettings__c.getInstance('settings');
        if (settings == null)
        {
            return new PageReference('/apex/Exception');
        }
        String consumerKey = settings.Consumer_Key__c;
        String userToken = ApexPages.currentPage().getParameters().get('userToken');
        String baseUrl = 'https://login.salesforce.com/services/oauth2/authorize?response_type=code&client_id=' + consumerKey;
        baseUrl += '&redirect_uri=' + settings.Redirect_URL__c;
        baseUrl += '&state=';
        String targetUrl = baseUrl + userToken;
        PageReference targetPage = new PageReference(targetUrl);
        targetPage.setRedirect(true);
        return targetPage;
    }
}